---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.14-alpine
    commands:
      - make build
  - name: publish-test
    image: plugins/docker:18
    settings:
      dockerfile: docker/Dockerfile.test
      repo: rocketprotocol/rocketzone-relayer-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
    when:
      event:
        - push
      branch: master
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]
---
kind: signature
hmac: 263c1c6e431cad1d0d133070dcac43f6efa74ebd630e6f332bb9d952c5cb3b79
