---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang:1.14
    commands:
      - make install
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]
  - name: publish-test
    image: plugins/docker:18
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/Dockerfile.test
      repo: rocketprotocol/rocketzone-relayer-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
      branch: master
---
kind: signature
hmac: bd101a365bae67421e61e89593249db067ffe71f7b48894348f73c9a00535c09
