---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.14.2
    commands:
      - ./contrib/build.sh
  - name: publish-test
    image: plugins/docker:18
    settings:
      dockerfile: docker/Dockerfile.test
      repo: rocketprotocol/rocketzone-relayer-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
    when:
      event:
        - push
      branch: ibc
  - name: deploy-devnet
    image: appleboy/drone-scp
    settings:
      username: ubuntu
      host: 
        from_secret: devnet_host
      key:
        from_secret: deploy_key
      target: 
        from_secret: deploy_home
      source:
        - bin/
    when:
      branch: devnet
  - name: deploy-devnet
    image: appleboy/drone-ssh
    settings:
      username: ubuntu
      host: 
        from_secret: devnet_host
      key:
        from_secret: deploy_key
      target: 
        from_secret: deploy_home
      script:
        - sh ~/deploy-devnet.sh
    when:
      branch: devnet
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]
---
kind: signature
hmac: 6a42470e9caf4bc106f3969a6d2a7346002b8df977a9f7fab219079f8970f532

