---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.14.1-alpine
    commands:
      - make build
  - name: publish-test
    image: plugins/docker:18
    settings:
      dockerfile: docker/Dockerfile.test
      repo: rocketprotocol/rocketzone-relayer-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
    when:
      event:
        - push
      branch: master
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]
---
kind: signature
hmac: 789fb1f4ead387ee2ff98ba76039da068494cbb01b2f98fa4b96bd3261b415e1
