---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.14
    commands:
      - make build
  - name: publish-test
    image: plugins/docker:18
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/Dockerfile.test
      repo: rocketprotocol/rocketzone-relayer-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
      branch: master
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]
---
kind: signature
hmac: 5e54799710b3fee33767dffabca1c9b1e384922317a90f59017f00301ed30253
