---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.14
    commands:
      - make build
  - name: publish-test
    image: plugins/docker:18
    settings:
      dockerfile: docker/Dockerfile.test
      repo: rocketprotocol/rocketzone-relayer-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
    when:
      event:
        - push
      branch: master
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]
---
kind: signature
hmac: 0ef8fe267302accb4ba3e77f8d3d33586f1930f243becd92fcbdecb02f8329a0
