---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.14.1-alpine
    commands:
      - ./contrib/build.sh
  - name: publish-test
    image: plugins/docker:18
    settings:
      dockerfile: docker/Dockerfile.test
      repo: rocketprotocol/rocketzone-relayer-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
    when:
      event:
        - push
      branch: ibc
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]
---
kind: signature
hmac: 650f43ab3d611d4e1305345af94df4df4426771900c9e454e246ac927f54c034
