before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/staked/
    id: 'staked'
    binary: staked
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -X "github.com/cosmos/cosmos-sdk/version.Name=StakeApp"
      - -X github.com/cosmos/cosmos-sdk/version.ServerName=staked
      - -X github.com/cosmos/cosmos-sdk/version.ClientName=stakecli
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}

  - main: ./cmd/stakecli/
    id: 'stakecli'
    binary: stakecli
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -X "github.com/cosmos/cosmos-sdk/version.Name=StakeApp"
      - -X github.com/cosmos/cosmos-sdk/version.ServerName=staked
      - -X github.com/cosmos/cosmos-sdk/version.ClientName=stakecli
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
archives:
  - replacements:
      darwin: mac

release:
  github:
    owner: public-awesome
    name: stakebird
  draft: true
  prerelease: auto

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  skip: true
